import sys

import parseUtil
from parseHeader import *
from parseSource import *
from htmlReportWriters import SimpleHTMLReportWriter
from detailedHTMLReportWriter import *

"""
Ideas:
- Report errors as UpdateAllViews calls might be hidden in those files.
- Search for class declarations in source files.

Bugs:


Refactorings:
- Detailed Report to use htmlReportWriters.
- Extract specific patterns RE from parsers. Allow to search for different Keywords. Max 2 REs (for diff param lists)
"""

"""
-- IMPORTANT INFO --
- Transactions.html file is not generated by this file. Use mainTransactions.py to generate it once you have run this
file.
"""


def add_category_to_file_dict(file_dict, catstr, file_info):
    if not file_dict.get(catstr):
        file_dict[catstr] = list()
    file_dict[catstr].append(file_info)


def make_file_for_category(file_dict, catstr, dir_path, file_name):
    file_path = os.path.join(dir_path, file_name)

    with open(file_path, "w") as fh:
        for file_info in file_dict[catstr]:
            the_file_path = file_info[0]
            counts = file_info[1:]
            fh.write("{file_path}     fulls={full} partials={partial}".format(
                file_path=the_file_path, full=counts[0], partial=counts[1]))
            fh.write("\n")


def make_htmlfile_for_category(file_dict, catstr, dir_path, file_name):
    file_path = os.path.join(dir_path, file_name)
    with open(file_path, "w") as fh:
        writer = SimpleHTMLReportWriter(fh)
        writer.write(file_dict, catstr)


def make_html_detailed_report_for_categories(final_dir, file_dict, categories):
    for cat in categories:
        cat_key = cat[0]
        cat_file_name = cat[1]
        with open(os.path.join(final_dir, cat_file_name), "w") as fh:
            writer = DetailedHTMLReportWriter(fh)
            writer.write(file_dict, cat_key)


def parse(path_to_search, dir_for_output):
    file_list = list()
    file_dict = dict()

    patt_editmodemgr = re.compile("EditModeMgr")
    patt_editor = re.compile("Editor")
    patt_handler = re.compile("Handler")
    patt_dialog = re.compile("Dialog")
    patt_element = re.compile("Elem")

    EDITMODEMGR_KEY = "EditModeMgr"
    EDITORS_KEY = "Editors"
    HANDLERS_KEY = "Handlers"
    DIALOGS_KEY = "Dialogs"
    ELEMENT_KEY = "Element"
    OTHERS_KEY = "Others"
    for root, dirs, files in os.walk(path_to_search):
        for file in files:
            ext = os.path.splitext(file)[1]
            file_path = os.path.join(root, file)
            if ext == ".cpp":
                result = parse_file(file_path)
                if result[0]:
                    header_dict = parse_header(file_path)
                    line_counts = result[1:]
                    file_list.append((file_path, line_counts))

                    result_editmode_mgr = patt_editmodemgr.search(file_path)
                    result_editor = patt_editor.search(file_path)
                    result_handler = patt_handler.search(file_path)
                    result_dialog = patt_dialog.search(file_path)
                    result_elem = patt_element.search(file_path)

                    # see parse_file for what is in result.
                    file_info = (file_path, result[1], result[2], result[3], result[4], header_dict)
                    if result_editmode_mgr:
                        add_category_to_file_dict(file_dict, EDITMODEMGR_KEY, file_info)

                    if result_editor:
                        add_category_to_file_dict(file_dict, EDITORS_KEY, file_info)
                    elif result_handler:
                        add_category_to_file_dict(file_dict, HANDLERS_KEY, file_info)
                    elif result_dialog:
                        add_category_to_file_dict(file_dict, DIALOGS_KEY, file_info)
                    elif result_elem:
                        add_category_to_file_dict(file_dict, ELEMENT_KEY, file_info)
                    else:
                        add_category_to_file_dict(file_dict, OTHERS_KEY, file_info)

    full = 0
    partial = 0
    for info in file_list:
        print("Found in {file_path}".format(file_path=info[0]))
        counts = info[1]
        full = full + counts[0]
        partial = partial + counts[1]

    total = full + partial
    print("-------------------------------")
    final_line = "Found {count} files for {full} fulls and {partial} partials for a total of {total}".format(
        count=len(file_list), full=full, partial=partial, total=total)
    print(final_line)

    final_dir = os.path.join(dir_for_output, "dist")
    with open(os.path.join(final_dir, "results.txt"), "w") as final_fh:
        final_fh.write(final_line)
        final_fh.write("\n")

    make_htmlfile_for_category(file_dict, EDITMODEMGR_KEY, final_dir, "editmodemgr.html")
    make_htmlfile_for_category(file_dict, EDITORS_KEY, final_dir, "editors.html")
    make_htmlfile_for_category(file_dict, HANDLERS_KEY, final_dir, "handlers.html")
    make_htmlfile_for_category(file_dict, DIALOGS_KEY, final_dir, "dialogs.html")
    make_htmlfile_for_category(file_dict, ELEMENT_KEY, final_dir, "element.html")
    make_htmlfile_for_category(file_dict, OTHERS_KEY, final_dir, "others.html")

    make_file_for_category(file_dict, EDITMODEMGR_KEY, final_dir, "editmodemgr.txt")
    make_file_for_category(file_dict, EDITORS_KEY, final_dir, "editors.txt")
    make_file_for_category(file_dict, HANDLERS_KEY, final_dir, "handlers.txt")
    make_file_for_category(file_dict, DIALOGS_KEY, final_dir, "dialogs.txt")
    make_file_for_category(file_dict, ELEMENT_KEY, final_dir, "element.txt")
    make_file_for_category(file_dict, OTHERS_KEY, final_dir, "others.txt")

    cat_list = [(EDITMODEMGR_KEY, "editmodemgr_detail.html"),
                (EDITORS_KEY, "editors_detail.html"),
                (HANDLERS_KEY, "handlers_detail.html"),
                (DIALOGS_KEY, "dialogs_detail.html"),
                (ELEMENT_KEY, "element_detail.html"),
                (OTHERS_KEY, "others_detail.html")]

    make_html_detailed_report_for_categories(final_dir, file_dict, cat_list)


def parse_file(file_path):
    src_parser = ParseSource()
    return src_parser.parse(file_path)


def parse_header(source_file_path):
    header_path = parseUtil.find_existing_header_path_with_source(source_file_path)
    if os.path.exists(header_path):
        return ParseHeader().parse(header_path)
    else:
        print("Path doesn't exist {path}".format(path=header_path))

    return dict()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Missing path for files to parse.")
    else:
        path = sys.argv[1]
        script_path = sys.argv[0]
        script_dir = os.path.dirname(script_path)
        parse(path, script_dir)
